-- CHG-171 — Contrato de mejora de «La Mulera» + rastreo GPS del
-- conductor. Idempotente; preserva los transportes existentes (los
-- campos nuevos quedan NULL en el histórico y la obligatoriedad para
-- registros nuevos la exige la validación de negocio, §62 del
-- contrato).

-- 1) Conductor (documento y teléfono cifrados con Fernet, §30/§59) y
--    tractocamión; hitos del viaje para el rastreo.
ALTER TABLE disaster_service.humanitarian_transports
    ADD COLUMN IF NOT EXISTS driver_full_name TEXT,
    ADD COLUMN IF NOT EXISTS driver_document_type TEXT,
    ADD COLUMN IF NOT EXISTS driver_document_number_encrypted BYTEA,
    ADD COLUMN IF NOT EXISTS driver_phone_encrypted BYTEA,
    ADD COLUMN IF NOT EXISTS tractor_plate TEXT,
    ADD COLUMN IF NOT EXISTS trailer_plate TEXT,
    ADD COLUMN IF NOT EXISTS vehicle_visible_characteristics TEXT,
    ADD COLUMN IF NOT EXISTS departed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMPTZ;

-- 2) Trayectoria del viaje: cada lectura del GPS del conductor.
CREATE TABLE IF NOT EXISTS disaster_service.humanitarian_transport_positions (
    id BIGSERIAL PRIMARY KEY,
    transport_id UUID NOT NULL
        REFERENCES disaster_service.humanitarian_transports(id)
        ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL
        CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL
        CHECK (longitude BETWEEN -180 AND 180),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS humanitarian_transport_positions_trip_idx
    ON disaster_service.humanitarian_transport_positions
    (transport_id, recorded_at DESC);

-- 3) Catálogo de ciudades/municipios de Colombia (§50): capitales y
--    municipios principales por departamento. El endpoint del catálogo
--    lo UNE con los municipios reales de acopios publicados, así que
--    una ciudad con centros nunca queda fuera aunque no esté sembrada.
CREATE TABLE IF NOT EXISTS disaster_service.transport_cities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    department TEXT NOT NULL,
    UNIQUE (name, department)
);

INSERT INTO disaster_service.transport_cities (name, department) VALUES
    ('Leticia', 'Amazonas'),
    ('Puerto Nariño', 'Amazonas'),
    ('Medellín', 'Antioquia'),
    ('Bello', 'Antioquia'),
    ('Itagüí', 'Antioquia'),
    ('Envigado', 'Antioquia'),
    ('Sabaneta', 'Antioquia'),
    ('La Estrella', 'Antioquia'),
    ('Caldas', 'Antioquia'),
    ('Copacabana', 'Antioquia'),
    ('Girardota', 'Antioquia'),
    ('Barbosa', 'Antioquia'),
    ('Rionegro', 'Antioquia'),
    ('Apartadó', 'Antioquia'),
    ('Turbo', 'Antioquia'),
    ('Caucasia', 'Antioquia'),
    ('Puerto Berrío', 'Antioquia'),
    ('Andes', 'Antioquia'),
    ('Santa Fe de Antioquia', 'Antioquia'),
    ('Urrao', 'Antioquia'),
    ('Arauca', 'Arauca'),
    ('Arauquita', 'Arauca'),
    ('Saravena', 'Arauca'),
    ('Tame', 'Arauca'),
    ('Barranquilla', 'Atlántico'),
    ('Soledad', 'Atlántico'),
    ('Malambo', 'Atlántico'),
    ('Sabanalarga', 'Atlántico'),
    ('Baranoa', 'Atlántico'),
    ('Galapa', 'Atlántico'),
    ('Puerto Colombia', 'Atlántico'),
    ('Bogotá', 'Bogotá D.C.'),
    ('Cartagena de Indias', 'Bolívar'),
    ('Magangué', 'Bolívar'),
    ('El Carmen de Bolívar', 'Bolívar'),
    ('Turbaco', 'Bolívar'),
    ('Arjona', 'Bolívar'),
    ('Mompós', 'Bolívar'),
    ('Tunja', 'Boyacá'),
    ('Duitama', 'Boyacá'),
    ('Sogamoso', 'Boyacá'),
    ('Chiquinquirá', 'Boyacá'),
    ('Paipa', 'Boyacá'),
    ('Puerto Boyacá', 'Boyacá'),
    ('Villa de Leyva', 'Boyacá'),
    ('Manizales', 'Caldas'),
    ('La Dorada', 'Caldas'),
    ('Chinchiná', 'Caldas'),
    ('Villamaría', 'Caldas'),
    ('Riosucio', 'Caldas'),
    ('Anserma', 'Caldas'),
    ('Florencia', 'Caquetá'),
    ('San Vicente del Caguán', 'Caquetá'),
    ('Puerto Rico', 'Caquetá'),
    ('El Doncello', 'Caquetá'),
    ('Yopal', 'Casanare'),
    ('Aguazul', 'Casanare'),
    ('Villanueva', 'Casanare'),
    ('Paz de Ariporo', 'Casanare'),
    ('Tauramena', 'Casanare'),
    ('Popayán', 'Cauca'),
    ('Santander de Quilichao', 'Cauca'),
    ('Puerto Tejada', 'Cauca'),
    ('Patía', 'Cauca'),
    ('Guapi', 'Cauca'),
    ('Valledupar', 'Cesar'),
    ('Aguachica', 'Cesar'),
    ('Codazzi', 'Cesar'),
    ('Bosconia', 'Cesar'),
    ('El Copey', 'Cesar'),
    ('Curumaní', 'Cesar'),
    ('Quibdó', 'Chocó'),
    ('Istmina', 'Chocó'),
    ('Tadó', 'Chocó'),
    ('Riosucio', 'Chocó'),
    ('Acandí', 'Chocó'),
    ('Bahía Solano', 'Chocó'),
    ('Montería', 'Córdoba'),
    ('Cereté', 'Córdoba'),
    ('Sahagún', 'Córdoba'),
    ('Lorica', 'Córdoba'),
    ('Montelíbano', 'Córdoba'),
    ('Planeta Rica', 'Córdoba'),
    ('Tierralta', 'Córdoba'),
    ('Soacha', 'Cundinamarca'),
    ('Girardot', 'Cundinamarca'),
    ('Zipaquirá', 'Cundinamarca'),
    ('Facatativá', 'Cundinamarca'),
    ('Chía', 'Cundinamarca'),
    ('Mosquera', 'Cundinamarca'),
    ('Madrid', 'Cundinamarca'),
    ('Funza', 'Cundinamarca'),
    ('Fusagasugá', 'Cundinamarca'),
    ('Cajicá', 'Cundinamarca'),
    ('Sibaté', 'Cundinamarca'),
    ('Tocancipá', 'Cundinamarca'),
    ('La Calera', 'Cundinamarca'),
    ('Villeta', 'Cundinamarca'),
    ('Ubaté', 'Cundinamarca'),
    ('Inírida', 'Guainía'),
    ('San José del Guaviare', 'Guaviare'),
    ('Neiva', 'Huila'),
    ('Pitalito', 'Huila'),
    ('Garzón', 'Huila'),
    ('La Plata', 'Huila'),
    ('Campoalegre', 'Huila'),
    ('Riohacha', 'La Guajira'),
    ('Maicao', 'La Guajira'),
    ('Uribia', 'La Guajira'),
    ('Manaure', 'La Guajira'),
    ('San Juan del Cesar', 'La Guajira'),
    ('Fonseca', 'La Guajira'),
    ('Santa Marta', 'Magdalena'),
    ('Ciénaga', 'Magdalena'),
    ('Fundación', 'Magdalena'),
    ('El Banco', 'Magdalena'),
    ('Plato', 'Magdalena'),
    ('Zona Bananera', 'Magdalena'),
    ('Villavicencio', 'Meta'),
    ('Acacías', 'Meta'),
    ('Granada', 'Meta'),
    ('Puerto López', 'Meta'),
    ('La Macarena', 'Meta'),
    ('Puerto Gaitán', 'Meta'),
    ('Pasto', 'Nariño'),
    ('Tumaco', 'Nariño'),
    ('Ipiales', 'Nariño'),
    ('Túquerres', 'Nariño'),
    ('La Unión', 'Nariño'),
    ('Cúcuta', 'Norte de Santander'),
    ('Ocaña', 'Norte de Santander'),
    ('Pamplona', 'Norte de Santander'),
    ('Villa del Rosario', 'Norte de Santander'),
    ('Los Patios', 'Norte de Santander'),
    ('Tibú', 'Norte de Santander'),
    ('Mocoa', 'Putumayo'),
    ('Puerto Asís', 'Putumayo'),
    ('Orito', 'Putumayo'),
    ('Valle del Guamuez', 'Putumayo'),
    ('Armenia', 'Quindío'),
    ('Calarcá', 'Quindío'),
    ('Montenegro', 'Quindío'),
    ('La Tebaida', 'Quindío'),
    ('Quimbaya', 'Quindío'),
    ('Pereira', 'Risaralda'),
    ('Dosquebradas', 'Risaralda'),
    ('Santa Rosa de Cabal', 'Risaralda'),
    ('La Virginia', 'Risaralda'),
    ('San Andrés', 'San Andrés y Providencia'),
    ('Providencia', 'San Andrés y Providencia'),
    ('Bucaramanga', 'Santander'),
    ('Floridablanca', 'Santander'),
    ('Girón', 'Santander'),
    ('Piedecuesta', 'Santander'),
    ('Barrancabermeja', 'Santander'),
    ('San Gil', 'Santander'),
    ('Socorro', 'Santander'),
    ('Málaga', 'Santander'),
    ('Barbosa', 'Santander'),
    ('Vélez', 'Santander'),
    ('Lebrija', 'Santander'),
    ('Sabana de Torres', 'Santander'),
    ('Sincelejo', 'Sucre'),
    ('Corozal', 'Sucre'),
    ('San Marcos', 'Sucre'),
    ('Tolú', 'Sucre'),
    ('San Onofre', 'Sucre'),
    ('Ibagué', 'Tolima'),
    ('Espinal', 'Tolima'),
    ('Melgar', 'Tolima'),
    ('Honda', 'Tolima'),
    ('Líbano', 'Tolima'),
    ('Chaparral', 'Tolima'),
    ('Mariquita', 'Tolima'),
    ('Cali', 'Valle del Cauca'),
    ('Palmira', 'Valle del Cauca'),
    ('Buenaventura', 'Valle del Cauca'),
    ('Tuluá', 'Valle del Cauca'),
    ('Buga', 'Valle del Cauca'),
    ('Cartago', 'Valle del Cauca'),
    ('Jamundí', 'Valle del Cauca'),
    ('Yumbo', 'Valle del Cauca'),
    ('Candelaria', 'Valle del Cauca'),
    ('Florida', 'Valle del Cauca'),
    ('Sevilla', 'Valle del Cauca'),
    ('Zarzal', 'Valle del Cauca'),
    ('Mitú', 'Vaupés'),
    ('Puerto Carreño', 'Vichada'),
    ('La Primavera', 'Vichada'),
    ('Cumaribo', 'Vichada')
ON CONFLICT (name, department) DO NOTHING;
